name: glowguard_app
description: "GlowGuard AI â€“ Chemical Safety Scanner"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase Core
  firebase_core: ^3.6.0

  # ðŸ” Authentication
  firebase_auth: ^5.3.1

  # ðŸ—„ Firestore database
  cloud_firestore: ^5.4.1

  # â˜ Storage for Before/After images
  firebase_storage: ^12.3.2

  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.18.1

  # ðŸ“¸ Image picking
  image_picker: ^1.0.4
  file_picker: ^8.0.6

  # ðŸ¤– ML
  image: ^4.1.7
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ml/best_ingredient_model.tflite
    - assets/ml/labels.txt
